=== claritychallenge/clarity_CC/clarity_CEC1/data_test/clarity_data/metadata/schemas/masker_nonspeech_list_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": 
      {
        "type": "object",
        "properties": {
          "ID": {
            "type": "string",
            "pattern": "^CIN_[a-z]*_[0-9]{3}$"
          },
          "class": {
            "type": "string"
          },
          "source": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "dataset": {
            "type": "string",
            "enum": ["train", "dev", "eval"]
          },
          "type": {
            "type": "string",
            "const": "noise"
          },
          "nsamples": {
            "type": "integer",
            "minimum": 0
          },
          "duration": {
            "type": "number"
          },
          "fs": {
            "type": "integer",
            "const": 44100
          }
        },
        "required": [
          "ID",
          "class",
          "source",
          "file",
          "dataset",
          "type",
          "nsamples",
          "duration",
          "fs"
        ]
      }
  }

=== claritychallenge/clarity_CC/clarity_CEC1/data_test/clarity_data/metadata/masker_nonspeech_list.dev.json
[
  {
    "ID": "CIN_fan_003",
    "class": "ElectricFan",
    "source": "Toronto",
    "file": "https://tspace.library.utoronto.ca/bitstream/1807/66304/9/09.%20VENTILATION%20AB.wav",
    "dataset": "dev",
    "type": "noise",
    "nsamples": 13230013,
    "duration": 300.0002947845805,
    "fs": 44100
  }
]
