=== claritychallenge/clarity_CC/clarity_CEC1/data_test/clarity_data/metadata/schemas/target_speech_list_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "prompt": {
          "type": "string"
        },
        "prompt_id": {
          "type": "string",
          "pattern": "^[0-9A-Z]{3}_[0-9]{5}$"
        },
        "speaker": {
          "type": "string",
          "pattern": "^T[0-9]{3}$"
        },
        "wavfile": {
          "type": "string",
          "pattern": "^T[0-9]{3}_[0-9A-Z]{3}_[0-9]{5}(x[2-5])?$"
        },
        "index": {
          "type": "integer",
          "minimum": 1,
          "maximum": 255
        },
        "dot": {
          "type": "string"
        },
        "sex": {
          "type": "string",
          "enum": ["M", "F"]
        },
        "dataset": {
          "type": "string"
        },
        "nsamples": {
          "type": "integer"
        },
        "fs": {
          "type": "integer",
          "const": 44100
        },
        "duration": {
          "type": "number",
          "minimum": 1.0,
          "maximum": 8.0
        }
      },
      "required": [
        "prompt",
        "prompt_id",
        "speaker",
        "wavfile",
        "index",
        "dot",
        "sex",
        "dataset",
        "nsamples",
        "fs",
        "duration"
      ]
    },
    "additionalItems": false
  }

=== claritychallenge/clarity_CC/clarity_CEC1/data_test/clarity_data/metadata/target_speech_list.dev.json
[
  {
    "prompt": "'All hot air and not much more,â€™ said Gloria.",
    "prompt_id": "AC5_02904",
    "speaker": "T013",
    "wavfile": "T013_AC5_02904",
    "index": 8,
    "dot": "All hot air and not much more said Gloria",
    "dataset": "dev",
    "sex": "F",
    "nsamples": 157437,
    "duration": 3.57,
    "fs": 44100
  }
]

=== claritychallenge/clarity_CC/clarity_CEC1/data_test/clarity_data/metadata/target_speech_list.train.json
[
  {
    "prompt": "The problem was that you didn't know.",
    "prompt_id": "JYD_04274",
    "speaker": "T005",
    "wavfile": "T005_JYD_04274",
    "index": 59,
    "dot": "The problem was that you didn\\'t know",
    "dataset": "train",
    "sex": "M",
    "nsamples": 109809,
    "duration": 2.49,
    "fs": 44100
  }
]
